fix: added option to use application url for domain's cookies
greenpress/authentication-service pull request #31
Opened 2021-02-23 19:28 UTC by drorrose

@davidmeirlevy 
We didn't have a domain to test the changes on, so please do?

2021-02-24 09:14 UTC, davidmeirlevy requested changes

2021-02-24 09:14 UTC, davidmeirlevy commented on config/index.js
>  	mongoUri: process.env.MONGO_URI || "mongodb://localhost/auth-service",
In this case - don't use a fallback value. Especially not my domain :).

2021-02-24 09:14 UTC, davidmeirlevy commented on server/services/tokens.js
> +	const finalUrl = '.' + new URL(applicationUrl).hostname
The app url will probably be a full URL including protocol and "www".
They should be removed and changed programmatically (and once, not on each cookie set).

2021-02-24 20:54 UTC, drorrose commented on config/index.js
>  	mongoUri: process.env.MONGO_URI || "mongodb://localhost/auth-service",
Done :)

2021-02-24 20:56 UTC, drorrose commented on server/services/tokens.js
> +	const finalUrl = '.' + new URL(applicationUrl).hostname
@davidmeirlevy 
const finalUrl = '.' + new URL(applicationUrl).hostname
This line should do it, as the hostname will return only the domain itself. 

I definitely agree with the single handling for the URL settings, so I fixed that, and I added a dedicated function to get the needed cookie parameters. Hopefully, this should do the trick, but let me know if it doesn't.

2021-02-25 09:12 UTC, davidmeirlevy requested changes

2021-02-25 09:12 UTC, davidmeirlevy commented on server/services/tokens.js
> +	finalDomainUrl = '.' + new URL(applicationUrl).hostname
I don't believe it's enough.
let's say the domain is: https://www.facebook.com

Will it be converted to ".facebook.com"? ("www" should be removed too).

2021-02-26 15:57 UTC, drorrose commented on server/services/tokens.js
> +	finalDomainUrl = '.' + new URL(applicationUrl).hostname
You are right, the "www" is not removed. The last commit handles it!

2021-02-26 17:50 UTC, davidmeirlevy approved these changes

2021-02-26 18:33 UTC, merged